# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, to='wiki.Tag'),
        ),
    ]
