# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='summary here', max_length=200),
            preserve_default=False,
        ),
    ]
