# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('deleted', '已删除')], default='published', max_length=20),
            preserve_default=False,
        ),
    ]
