# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PGFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Full file name')),
                ('oid', models.PositiveIntegerField(verbose_name='PostgreSQL LargeObject OID')),
                ('size', models.PositiveIntegerField(verbose_name='File size in bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pgfile',
                'required_db_vendor': 'postgresql',
            },
        ),
    ]
