# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import webfs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=webfs.models.upload_to)),
                ('mimetype', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('metadata', webfs.models.JsonField(max_length=256, use_db_null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
